on:
  push:

name: Sonar_27022024

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=pankuk0
          -Dsonar.projectKey=Pankuk0_lab
          -Dsonar.host.url=https://sonarcloud.io/
          -X
      env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Check Quality Gate
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        # Espera a que SonarCloud procese los resultados del análisis
        sleep 20
        # Reemplaza 'YourSonarProjectKey' con tu projectKey real
        projectKey="Pankuk0_lab"
        # Reemplaza 'YourOrganization' con tu organización real de SonarCloud
        organization="pankuk0"
        # Obtiene el Quality Gate status de SonarCloud
        response=$(curl -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Pankuk0_lab&organization=pankuk0")
        echo $response
        # Falla si el status del Quality Gate es diferente de 'OK'
        if [[ $(echo $response | grep '"status":"OK"') == "" ]]; then
          echo "Quality Gate failed!"
          exit 1
        fi

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      with:
          project: 'Pankuk0_lab'
          path: '.'
          format: 'HTML'

    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports
