name: SAST-AlvaroCastillo

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -X
          -Dsonar.organization="Pankuk0"
          -Dsonar.projectKey="lab"
          -Dsonar.sources=.
